export const skillReferences = [
	{
		id: 0,
		name: 'Attack',
		url: 'https://runescape.wiki/images/Attack-icon.png',
		order: 1,
	},
	{
		id: 3,
		name: 'Constitution',
		url: 'https://runescape.wiki/images/Constitution-icon.png',
		order: 2,
	},
	{
		id: 1,
		name: 'Defence',
		url: 'https://runescape.wiki/images/Defence-icon.png',
		order: 7,
	},
	{
		id: 2,
		name: 'Strength',
		url: 'https://runescape.wiki/images/Strength-icon.png',
		order: 4,
	},

	{
		id: 4,
		name: 'Ranged',
		url: 'https://runescape.wiki/images/Ranged-icon.png',
		order: 10,
	},
	{
		id: 5,
		name: 'Prayer',
		url: 'https://runescape.wiki/images/Prayer-icon.png',
		order: 13,
	},
	{
		id: 6,
		name: 'Magic',
		url: 'https://runescape.wiki/images/Magic-icon.png',
		order: 16,
	},
	{
		id: 7,
		name: 'Cooking',
		url: 'https://runescape.wiki/images/Cooking-icon.png',
		order: 12,
	},
	{
		id: 8,
		name: 'Woodcutting',
		url: 'https://runescape.wiki/images/Woodcutting-icon.png',
		order: 18,
	},
	{
		id: 9,
		name: 'Fletching',
		url: 'https://runescape.wiki/images/Fletching-icon.png',
		order: 17,
	},
	{
		id: 10,
		name: 'Fishing',
		url: 'https://runescape.wiki/images/Fishing-icon.png',
		order: 9,
	},
	{
		id: 11,
		name: 'Firemaking',
		url: 'https://runescape.wiki/images/Firemaking-icon.png',
		order: 15,
	},
	{
		id: 12,
		name: 'Crafting',
		url: 'https://runescape.wiki/images/Crafting-icon.png',
		order: 14,
	},
	{
		id: 13,
		name: 'Smithing',
		url: 'https://runescape.wiki/images/Smithing-icon.png',
		order: 6,
	},
	{
		id: 14,
		name: 'Mining',
		url: 'https://runescape.wiki/images/Mining-icon.png',
		order: 3,
	},
	{
		id: 15,
		name: 'Herblore',
		url: 'https://runescape.wiki/images/Herblore-icon.png',
		order: 8,
	},
	{
		id: 16,
		name: 'Agility',
		url: 'https://runescape.wiki/images/Agility-icon.png',
		order: 5,
	},
	{
		id: 17,
		name: 'Thieving',
		url: 'https://runescape.wiki/images/Thieving-icon.png',
		order: 11,
	},
	{
		id: 18,
		name: 'Slayer',
		url: 'https://runescape.wiki/images/Slayer-icon.png',
		order: 20,
	},
	{
		id: 19,
		name: 'Farming',
		url: 'https://runescape.wiki/images/Farming-icon.png',
		order: 21,
	},
	{
		id: 20,
		name: 'Runecrafting',
		url: 'https://runescape.wiki/images/Runecrafting-icon.png',
		order: 19,
	},
	{
		id: 21,
		name: 'Hunter',
		url: 'https://runescape.wiki/images/Hunter-icon.png',
		order: 23,
	},
	{
		id: 22,
		name: 'Construction',
		url: 'https://runescape.wiki/images/Construction-icon.png',
		order: 22,
	},
	{
		id: 23,
		name: 'Summoning',
		url: 'https://runescape.wiki/images/Summoning-icon.png',
		order: 24,
	},
	{
		id: 24,
		name: 'Dungeoneering',
		url: 'https://runescape.wiki/images/Dungeoneering-icon.png',
		order: 25,
	},
	{
		id: 25,
		name: 'Divination',
		url: 'https://runescape.wiki/images/Divination-icon.png',
		order: 26,
	},
	{
		id: 26,
		name: 'Invention',
		url: 'https://runescape.wiki/images/Invention-icon.png',
		order: 27,
	},
	{
		id: 27,
		name: 'Archaeology',
		url: 'https://runescape.wiki/images/Archaeology-icon.png',
		order: 28,
	},
	{
		id: 28,
		name: 'Necromancy',
		url: 'https://runescape.wiki/images/Necromancy-icon.png',
		order: 29,
	},
]
